version: '3.1'

services:
    stage-application:
        container_name: stage-pks-galaxy-application
        image: waycambas/pks-galaxy
        ports:
            - "8089:80"
            - "449:443"
            - "9009:9000"
        hostname: pks-galaxy-application
        volumes:
            - ./images/application/app:/app
            - ./etc/stage/supervisor/supervisord.conf:/etc/supervisord.conf

            - ./data/stage/logs:/var/log/supervisor
            - ./app/stage:/usr/share/app
            - ./etc/stage/nginx/conf.d:/etc/nginx/conf.d
            - ./etc/stage/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/stage/php/php.ini:/etc/php.d/php.ini
        networks:
            - stage-pks-galaxy-net
        links:
            - stage-mariadb
            - stage-redis
            - stage-mongodb

        depends_on:
            - stage-mariadb
            - stage-redis
            - stage-mongodb

    stage-mariadb:
        container_name: stage-pks-galaxy-mariadb
        image: mariadb:10.3
        env_file:
            - ./environments/.env.stage
        restart: always
        networks:
            - stage-pks-galaxy-net
        ports:
            - "7877:3306"
        volumes:
            - ./data/stage/mariadb:/var/lib/mysql
            - ./etc/stage/my.cnf.d:/etc/mysql/conf.d
    stage-mongodb:
        container_name: stage-pks-galaxy-mongodb
        image: bitnami/mongodb:4.2
        env_file:
            - ./environments/.env.stage
        restart: always
        networks:
            - stage-pks-galaxy-net
        ports:
            - "27015:27017"
        volumes:
            - mongo-data-stage:/bitnami/mongodb
    stage-redis:
        container_name: stage-pks-galaxy-redis
        image: redis:4.0
        env_file:
            - ./environments/.env.stage
        command: ["redis-server", "/usr/stage/etc/redis/redis.conf", "--appendonly yes"]
        networks:
            - stage-pks-galaxy-net
        ports:
            - "6377:6379"
        volumes:
            - ./data/stage/redis:/data
            - ./etc/stage/redis/redis.conf:/usr/stage/etc/redis/redis.conf
    
networks:
    stage-pks-galaxy-net: {}
volumes:
    mongo-data-stage:
